### ISSUE TITLE
Add youtube field for groups

### ISSUE THREAD

**Issue by Mte90** [mozilla/community-portal#230]
As Mozilla Italia we have an youtube channel where we share oyour videos like our meetings call.
I add that url in other but add a specific field can improve the readbility https://community.mozilla.org/groups/mozilla-italia/

**Comment by nukeador** [comment]
I'm starting to wonder if we should add any social platform to the list of fields, or just allow groups to add more links with custom labels. What if my group uses peertube instead of youtube?

I don't want this list of platforms to feel like a recommendation of places where you should have presence. What about communities that have a mastodon account instead of twitter?

**Comment by ranjithrajv** [comment]
@nukeador 
An issue filed by me addressing a part of what you said, here https://github.com/mozilla/community-portal/issues/240

**Comment by couci** [comment]
Closing this one to keep one place for this conversation at #240
