### ISSUE TITLE
Option to Moderate Members of a Group

### ISSUE THREAD

**Issue by bobreyes** [mozilla/community-portal#257]
As early as now, I can see members joining groups at random. Perhaps if we could have a moderation or edit tool (for group creators/admins) to remove members. Thanks!

**Comment by LucyeoH** [comment]
@bobreyes in order to ensure that all groups are open and inclusive - we made a decision not to allow groups to exclude members at this time. 
However you can remind members to remove themselves if they're not active and we're open to find new ways to ensure the members of groups are active in the future. If you need to remove someone for CPG reasons you can always contact an admin.

**Comment by LucyeoH** [comment]
@bobreyes in order to ensure that all groups are open and inclusive - we made a decision not to allow groups to exclude members at this time. 
However you can remind members to remove themselves if they're not active and we're open to find new ways to ensure the members of groups are active in the future. If you need to remove someone for CPG reasons you can always contact an admin.

**Comment by bobreyes** [comment]
> @bobreyes in order to ensure that all groups are open and inclusive - we made a decision not to allow groups to exclude members at this time.
> However you can remind members to remove themselves if they're not active and we're open to find new ways to ensure the members of groups are active in the future. If you need to remove someone for CPG reasons you can always contact an admin.

Thanks, Lucy! Perhaps if we can have a search feature in the portal based on the country/location of a Mozillian so that it would be faster for us to know people from within the same area/community. Thanks!

**Comment by nukeador** [comment]
Yes, improved search capabilities are planed :-)

**Comment by couci** [comment]
Search capabilities have been added
