### ISSUE TITLE
Issues with setting up categories

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#302]
Since I was told this was the wrong place to edit categories, I removed them all from 

https://community.mozilla.org/wp-admin/edit-tags.php?taxonomy=event-categories&post_type=event 

This caused all events to lose their categories.

Then I update the categories from the right place:

https://community.mozilla.org/wp-admin/edit-tags.php?taxonomy=post_tag 

This made the first empty list now to be populated.

I also see that existing groups still display some old categories I removed/changed.

**Comment by kycapstick** [comment]
In response to the first part, the Events Manager plugin we're using to manage events was built to use it's own custom categories, but we wanted to leverage the one list of wordpress tags across the site. 

So there is functionality that runs every time you edit/create an event that matches the custom Events categories to the standard wordpress tags so that the two always match.
