### ISSUE TITLE
Event is fetching group hoasts as organizers

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#350]
When a member of a group is organizing an event the two group contacts appear as the event hoasts. Example: https://community.mozilla.org/events/women-in-tech/

While the event should stay hoasted by [group] The event hoast should be the organizer of the event and not the group contacts

**Comment by dnaluz** [comment]
I just checked this event it is not hosted by any group.

**Comment by dnaluz** [comment]
Also tested when the event is hosted by a group a link to the group is present.

**Comment by nukeador** [comment]
Someone might have changed the event in the meantime.

The change requested here is:

If an event is hosted by a group:
- The profile creating the group should be displayed as the organizer.
- Only the group name and link should be displayed.
- The group contacts shouldn't be listed as organizers (because they have no control over who created events on their group and it's misleading).

Thanks!

**Comment by dnaluz** [comment]
Fix is live
