### ISSUE TITLE
Enter shouldn't prompt the submit button

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/community-portal#352]
When we create an event and write something on the description field, it prompts submit action if we click enter while it shouldn't. 

I'm on Mac (Firefox 73.0.1)

**Comment by kelimuttu** [comment]
@nukeador

**Comment by dnaluz** [comment]
Implicit form submission is the default action for all standard browsers and accessibility.

**Comment by kelimuttu** [comment]
I was trying to add a line break, but it triggers submit action everytime I click enter. How am I  suppose to add line break, then?

**Comment by MichaelKohler** [comment]
Textareas should not submit the form when pressing ENTER. For input fields, that is indeed the standard behavior though.

See:

```
<form action="http://example.com" method="POST">
  <input name="foo" type="text">
  <textarea></textarea>
</form>
```

**Comment by nukeador** [comment]
Yes, description should be a textarea, because it's currently breaking the event creation flow for people when writing the description with multiple lines (which is a common usercase since they are also adding the agenda and bullet points).

In the future this should be improved to support some rich formatting, but for now let's just fix the issue.

**Comment by dnaluz** [comment]
The fix for this is live.  You can now use enters in textarea elements
