### ISSUE TITLE
Update event is not working when we click Edit location details

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/community-portal#499]
I was trying to update an event. Since I need to update the meeting link, I click Edit location details. However, once I put the details and click the Update Event button, the page doesn't do anything. It works when I don't click the Edit location details, though.

**Comment by cseas** [comment]
I'm facing the same issue. I'm trying to update the meeting link for [this](https://community.mozilla.org/events/mozilla-bangalore-hunt-from-home-phase-2/) event but `Update` button is not working.

Please resolve this urgently since the event will soon be conducted.

**Comment by dnaluz** [comment]
I just ran an update on a test event.  Everything seemed fine, could you provide more details?

**Comment by cseas** [comment]
Here's what I did exactly:
1. Create an event with the following location details:
`Is this event Online or on location?`: Online
`Online Meeting Link`: Provide URL
`Where will this event be held?`: Provide Country
`City`: Provide City

After doing this I realised the meeting link is not showing up on the event page. So I figured maybe it only shows up if you fill `Where will this event be held?` as Online Event too. But the `Update` button is not working when I'm trying to do that.

Anyhow, the main issue is that the meeting link is not showing up in [this](https://community.mozilla.org/events/mozilla-bangalore-hunt-from-home-phase-2/) event page even though I've added it to the event details.

**Comment by kycapstick** [comment]
@cseas took a look and have added a fix for this bug to the security overhaul we're currently completing on the entire site. So a fix will be coming with that. 

In the meantime, you can get around this error by changing the select labelled "is this event online or on location?" to "physical location" and then back to "online".

As for the link not appearing on the page, it's because the field currently requires a full url, including the https://

**Comment by davesenior** [comment]
This is being test on staging currently

**Comment by dnaluz** [comment]
Fixed
