### ISSUE TITLE
"View more topics" is not linking correctly on some groups

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#561]
On some groups like the Mozilla Brasil, the discourse bottom link "View more topics" is not linking to the category main page.

https://community.mozilla.org/groups/mozilla-brasil/

Currently linking to https://discourse.mozilla.org/t/topic/54844
Instead of https://discourse.mozilla.org/c/community-portal/mozilla-brasil/310

**Comment by dnaluz** [comment]
So it looks like the link is actually correct  

<img width="1457" alt="Screen Shot 2020-06-05 at 12 46 56 PM" src="https://user-images.githubusercontent.com/2521244/83902652-c98ac000-a72a-11ea-8df2-f97777f94738.png">

The issue seems to be a a styling issue where a link in the table is overlapping the view more link.

**Comment by dnaluz** [comment]
Fixed and deployed
