### ISSUE TITLE
Past events failed to be shown after page 3

### ISSUE THREAD

**Issue by greenbrown** [mozilla/community-portal#698]
Past events are only available for pages 1-3 (at first under past events show has up to 68 pages, but only 3 pages able to open).

<img width="1137" alt="Screenshot 2021-09-14 at 3 14 22 PM" src="https://user-images.githubusercontent.com/49750588/133223037-0580e91d-7ed8-42e3-9dbc-f42497f3004e.png">

How to replicate my case:

1. Open community.mozilla.org
2. Go to the "Events" menu
3. Click sub-menu "Past Events" under the search box
4. The first page works fine and it show has up to 68 pages
5. but when clicking page 2 or ">" next button, the page number available change only 3 pages. If you back to the first page and click page "68" on the bottom, it will show "There are currently no events.".

**Comment by Mte90** [comment]
This because is not showing at all the past events but still the last events...

**Comment by Mte90** [comment]
Ok so the issue is that HTML side the links are right but there is a redirect when the link https://community.mozilla.org/events/?pno=4&view=past is opened.
I see that there is a htaccess rewrite rule that auto append a trailing `/` but I don't have the access for this.

I don't think that is the javascript at https://github.com/mozilla/community-portal/blob/master/js/events.js that add that slash

**Comment by Mte90** [comment]
So on the staging website the issue is not happening https://mozportalstage.wpengine.com/it/events/?pno=2&view=past...

**Comment by Mte90** [comment]
So with JS disabled the issue is still happening so there are 2 options now, webserver or WordPress.

Webserver doesn't have any rules so the last option is wordpress and is not easy to debug.
I think that with an htaccess rule we can fix the issue without analyze what is happening. 
I am not that.

**Comment by Mte90** [comment]
Ok I can replicate the bug now on the dev instance so it is something on wordpress side.
