### ISSUE TITLE
Cannot create new event

### ISSUE THREAD

**Issue by bobreyes** [mozilla/community-portal#727]
Clicking on "**[organize your own](https://community.mozilla.org/en/events/edit-event/?action=edit)**" from https://community.mozilla.org/en/events/ leads to Error 404 (Page Not Found) at https://community.mozilla.org/en/events/edit-event/?action=edit

![Screen Shot 2022-02-26 at 23 44 37](https://user-images.githubusercontent.com/2232/155849419-dfab2149-0fa4-4337-b84f-cdf1d2cbc9c0.png)

**Comment by Mte90** [comment]
I am wondering of the changes of the other day create this issue. I will check in the next days.

**Comment by Mte90** [comment]
yes the bug is just in edit window and I am not able to understand where is the bug.

**Comment by Mte90** [comment]
I am trying to find a bugfix but the issue is happening only on production and not on staging and in my dev environment.
It seems that if I disable the event list with the page `events` now is working again but with the caching system in production is very difficult to do debug that issue. I am not sure at every test if there is the cache or not as example.

Maybe I have to set the website in maintenance so I can d all the tests I need to find what is broken.

**Comment by Mte90** [comment]
Seems that with the bad manners I was able to fix it :-)

**Comment by JuanVqz** [comment]
> Seems that with the bad manners I was able to fix it :-)

you are right! it's fixed, thank you!
