### ISSUE TITLE
Tags, locations and languages should be linked to search

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#90]
Each time we display a tag, location or a language, these should be linked to the corresponding search to see all occurrences.

- All members speaking a language
- All groups using the same tag
- All groups in the same country
- All groups in the same city
- All events using the same tag
- All events on the same initiative
- All events in the same city
- All events in the same country

**Comment by davesenior** [comment]
This is similar but not exactly like to #94

**Comment by dnaluz** [comment]
@nukeador.

For v1 we can definitely have a location link to the search results(groups and events) however since v1 does not include a site wide search it would be limited to the section they are in.  So for example if they click a tag or a location while in groups they would get redirected to the groups search page with the tag filtered.  This would go the same for events.  Currently we don't have functionality to search members by tag and location at the moment because of the privacy issues but we can definitely do a v1 implementation of this for events and groups.

**Comment by dnaluz** [comment]
PR: https://github.com/mozilla/community-portal/pull/99

This will link locations and tags for events and groups to the search page with query parameters passed.

**Comment by nukeador** [comment]
Sure, let's get what's possible, I totally understand. Thanks!

**Comment by dnaluz** [comment]
FIx is live for groups and events
